#ifndef PREAMBLE_GLSL
#define PREAMBLE_GLSL

// Blit
#define BLIT_TEXCOORD_VARYING_LOCATION 0
#define BLIT_TEXTURE_TEXURE_BINDING 0

// Shadow
#define SHADOW_MAP_LIGHT_SPACE_MATRIX_UNIFORM_LOCATION 0
#define SHADOW_MAP_MW_UNIFORM_LOCATION 4
#define SHADOW_DIFFUSE_MAP_TEXTURE_BINDING 0

// Scene
#define SCENE_POSITION_ATTRIB_LOCATION 0
#define SCENE_TEXCOORD_ATTRIB_LOCATION 1
#define SCENE_NORMAL_ATTRIB_LOCATION 2
#define SCENE_BONE_ID_ATTRIB_LOCATION 3
#define SCENE_BONE_WEIGHTS_ATTRIB_LOCATION 4

#define SCENE_MW_UNIFORM_LOCATION 0
#define SCENE_N_MW_UNIFORM_LOCATION 4
#define SCENE_MVP_UNIFORM_LOCATION 7
#define SCENE_CAMERAPOS_UNIFORM_LOCATION 11
#define SCENE_LIGHT_SPACE_MATRIX_UNIFORM_LOCATION 12
#define SCENE_LIGHT_POS 16
#define SCENE_LIGHT_COLOR 17
#define SCENE_TEXCOORD_SCALE 18
#define SCENE_TEXCOORD_OFFSET 19
#define SCENE_HAS_DIFFUSE_MAP_UNIFORM_LOCATION 20
#define SCENE_BONE_OFFSET_UNIFORM_LOCATION 21
#define SCENE_VIEW_UNIFORM_LOCATION 22
#define SCENE_PROJECTON_UNIFORM_LOCATION 26

#define SCENE_BONE_MAT_SSBO_BINDING 10
#define SCENE_INV_BIND_POSE_BINDING 11
#define SCENE_ANIM_POSE_BINDING 12

#define SCENE_DIFFUSE_MAP_TEXTURE_BINDING 0
#define SCENE_SHADOW_MAP_TEXTURE_BINDING 1

// Animation
#define MAX_BONE_INFLUENCE 4

// Skybox
#define SKYBOX_POSITION_ATTRIB_LOCATION 0
#define SKYBOX_PROJECTION_UNIFORM_LOCATION 0
#define SKYBOX_VIEW_UNIFORM_LOCATION 4

#define SKYBOX_TEXTURE_BINDING 0

// Post process
#define POST_PROCESS_ITIME_UNIFORM_LOCATION 0
#define POST_PROCESS_TEXTURE_BINDING 1

// SAT
#define SAT_WORKGROUP_SIZE_X 1024

#define SAT_READ_UINT_INPUT_UNIFORM_LOCATION 0
#define SAT_READ_WGSUM_UNIFORM_LOCATION 1
#define SAT_ADD_WGSUM_UNIFORM_LOCATION 2

#define SAT_INPUT_TEXTURE_BINDING 0
#define SAT_UINT_INPUT_TEXTURE_BINDING 1

#define SAT_OUTPUT_IMAGE_BINDING 0
#define SAT_WGSUMS_IMAGE_BINDING 1

// Transpose SAT
#define TRANSPOSE_SAT_WORKGROUP_SIZE_X 32

#define TRANSPOSE_SAT_INPUT_IMAGE_BINDING 0
#define TRANSPOSE_SAT_OUTPUT_IMAGE_BINDING 1

// DOF
#define DOF_ZNEAR_UNIFORM_LOCATION 0
#define DOF_FOCUS_UNIFORM_LOCATION 1

#define DOF_SAT_TEXTURE_BINDING 0
#define DOF_DEPTH_TEXTURE_BINDING 1

// Debug depth map
#define DEBUG_DEPTH_MAP_TEXURE_BINDING 0
#define DEBUG_DEPTH_MAP_NEAR_PLANE 1
#define DEBUG_DEPTH_MAP_FAR_PLANE 2

// Skinning compute
#define SKINNING_GROUP_SIZE_X 64
#define SKINNING_GROUP_SIZE_Y 1
#define SKINNING_GROUP_SIZE_Z 1

#define SKINNING_COMPUTE_INV_BIND_POSE_BINDING 0
#define SKINNING_COMPUTE_POSE_BINDING 1
#define SKINNING_COMPUTE_TRS_BINDING 2
#define SKINNING_COMP_BONE_COUNT_UNIFORM_LOCATION 3
#define SKINNING_COMP_SKELETON_OFFSET_UNIFORM_LOCATION 4

#endif // PREAMBLE_GLSL
